apiVersion: backstage.io/v1alpha1
kind: Template
metadata:
  name: templateScaffoldJava
  annotations:
    github.com/project-slug: carlosbioingeniero/templateScaffoldJava
spec:
  type: service
  lifecycle: unknown
  owner: guests
