apiVersion: scaffolder.backstage.io/v1beta3
# https://backstage.io/docs/features/software-catalog/descriptor-format#kind-template
kind: Template
metadata:
  name: Scaffold-Clean-Architecture
  title: Scaffold Clean Architecture Java
  description: Crea un artefacto basado en el Scaffold de Clean Architecture para Java
  tags: ['recommended', 'java', 'clean-architecture'] 
spec:
  owner: user:guest
  type: service

  # These parameters are used to generate the input form in the frontend, and are
  # used to gather input data for the execution of the template.
  parameters:
    - title: Ingrese los parámetros de configuracion
      required:
        - package
        - type
        - name

      properties:
        name:
          title: Name
          type: string
          description: Unique name of the component
          ui:autofocus: true
          ui:options:
            rows: 5
        package:
          title: Package
          type: string
          default: co.com.bancolombia
          ui:autofocus: true
          ui:options:
            rows: 5
        type:
          title: Type
          type: string
          description: reactive or imperative
          ui:autofocus: true
          ui:options:
            rows: 5
        coverage:
          title: Type
          type: string
          default: jacoco
          description: coverage
          ui:autofocus: true
          ui:options:
            rows: 5
        lombok:
          title: lombok
          type: boolean
          default: true
          description: true or false
          ui:autofocus: true
          ui:options:
            rows: 5

    - title: Credentials
      required:
        - accessToken
      properties:
        accessToken:
          title: accessToken
          type: string
          description: Token to execute back from Mauricio's repository
          ui:autofocus: true
          ui:widget: password
          ui:options:
            rows: 5


    #- title: Choose a location
    #  required:
    #    - repoUrl
    #  properties:
    #    repoUrl:
    #      title: Repository Location
    #      type: string
    #      ui:field: RepoUrlPicker
    #      ui:options:
    #        allowedHosts:
    #          - github.com

  # These steps are executed in the scaffolder backend, using data that we gathered
  # via the parameters above.
  steps:
    # Each step executes an action, in this case one templates files into the working directory.
    - id: fetch-base
      name: Fetch Base
      action: fetch:template
      input:
        url: ./content
        values:
          name: ${{ parameters.name }}

    # This step publishes the contents of the working directory to GitHub.
    - id: create
      name: Create
      action: github:actions:dispatch
      input:
        repoUrl: 'github.com?repo=build--scaffold&owner=maocq'
        workflowId: '32474166'
        branchOrTagName: main
        token: ${{ parameters.accessToken }}
        workflowInputs:
          data: '{"models" : ["User", "Juanes"], "useCases" : ["CreateUser", "NewAccount"]}'


    # The final step is to register our new component in the catalog.
    #- id: register
    #  name: Register
    #  action: catalog:register
    #  input: 
    #    repoContentsUrl: ${{ steps.publish.output.repoContentsUrl }}
    #    catalogInfoPath: '/catalog-info.yaml'

  # Outputs are displayed to the user after a successful execution of the template.
  output:
    links:
      - title: Repository
        url: ${{ steps.create.output.remoteUrl }}
      - title: Open in catalog
        icon: catalog
        entityRef: ${{ steps.register.output.entityRef }}
